--- #YAML:1.0
name:                Bundle-STBEY
version:             1.0
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector:                   7.1
    Carp::Clan:                    5.3
    Data::Locations:               5.4
    Date::Calc:                    6
    Date::Calc::Util:              1
    Date::Pcalc:                   6
    Math::MatrixBool:              5.8
    Set::IntRange:                 5.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
